twig:
    default_path: '%kernel.project_dir%/templates'
     exception_controller: 'twig.controller.exception::showAction'
    error_handler: null

when@test:
    twig:
        strict_variables: true